import Navbar from "@/components/Navbar";
import "./globals.css";
import { inter } from "@/data";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} bg-stone-300`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
